### ISSUE TITLE
rename data_grid()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/estimate#10]
otherwise will clash with modelr

**Comment by DominiqueMakowski** [comment]
But how though?

**Comment by DominiqueMakowski** [comment]
alternatives:

- `datagrid()`
- `reference_grid()`
- `reference_data()`
- `data_matrix()`

**Comment by strengejacke** [comment]
`data_matrix()` sounds good, but is it a problem if it clashes with _modelr_?

**Comment by DominiqueMakowski** [comment]
>  is it a problem if it clashes with modelr?

Yeah, I think so, I could see myself using it at the same time than easyverse... and it's good if we can avoid unnecessary conflicts with the tidyverse.

Maybe a more distinctive and explicit name would emphasize its name for visualisation?

- `visualisation_grid`
- `visualisation_data`
- `visualisation_matrix`

**Comment by DominiqueMakowski** [comment]
I think I like `visualisation_matrix`, because it echoes the matrix' matrix as a "fake" artificial world that has just the appearance of reality. Which is kind of close of when we visualise the links in a model: it's a polished, artificial and simple perspective more or less loosely connected to reality. And it's mainly used in the package for visualisation purposes...

**Comment by mattansb** [comment]
I like it!
is `vis_matrix` too short?

**Comment by DominiqueMakowski** [comment]
> is vis_matrix too short?

![image](https://media1.tenor.com/images/23189d456e0608040773536982af3b9b/tenor.gif)

(yes, natural language-like code FTW 😁)

**Comment by strengejacke** [comment]
`expand_grid()`? 🤷‍♂
