### ISSUE TITLE
data_grid: allow spread in terms of SD deviation from the mean

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/estimate#23]
cool feature implemented in ['interaction'](https://cran.r-project.org/web/packages/interactions/vignettes/interactions.html) package

**Comment by strengejacke** [comment]
?

**Comment by DominiqueMakowski** [comment]
To have something like that:

![image](https://user-images.githubusercontent.com/8875533/62431705-34aae500-b75c-11e9-8e25-c49a621c7e3e.png)

I wonder what is the best API design for that though. Maybe `length = "SD"` which could accept also variants like "2SD", "3SD" to increase the spread... but I don't really like string-based coding.

**Comment by strengejacke** [comment]
Ok, I see. Similar to [`values_at()`](https://strengejacke.github.io/ggeffects/reference/rprs_values.html).

For continuous variables, ggeffects automatically selects mean + SD. Maybe [this vignette](https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html) gives you some inspiration?

**Comment by DominiqueMakowski** [comment]
Done:

https://easystats.github.io/estimate/articles/data_grid.html#visualising-an-interaction-between-two-numeric-variables

![image](https://user-images.githubusercontent.com/8875533/62525622-4ed2e900-b86a-11e9-8288-0893e25409e3.png)
