### ISSUE TITLE
data_or_whatever_grid() options

### ISSUE THREAD

**Issue by strengejacke** [easystats/estimate#26]
Would be nice to have the option..

1. to also get the mode for `factors`
2. and to condition remaining variables on certain values.

See arguments `condition` and `typical` in [`new_data()`](https://strengejacke.github.io/ggeffects/reference/new_data.html), and the help for [`typical_value()`](https://strengejacke.github.io/sjmisc/reference/typical_value.html).

**Comment by DominiqueMakowski** [comment]
> and to condition remaining variables on certain values.

This is already in:

``` r
library(estimate)
visualisation_matrix(iris, target = "Sepal.Length", numerics = 0)
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1           4.3           0            0           0  setosa
#> 2           4.7           0            0           0  setosa
#> 3           5.1           0            0           0  setosa
#> 4           5.5           0            0           0  setosa
#> 5           5.9           0            0           0  setosa
#> 6           6.3           0            0           0  setosa
#> 7           6.7           0            0           0  setosa
#> 8           7.1           0            0           0  setosa
#> 9           7.5           0            0           0  setosa
#> 10          7.9           0            0           0  setosa
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

> to also get the mode for factors

Added to TODO ☺️

**Comment by strengejacke** [comment]
> This is already in:

I meant something like `target = "Sepal.Length", Sepal.Width = 10`, which does not set Sepal.Width to mean, but to ten, and all remaining to their mean.

**Comment by DominiqueMakowski** [comment]
Oh right.

**Comment by DominiqueMakowski** [comment]
I'd say that the most straightforward API for that would be to see if target contains a `=` sign, if yes split on it and assign righthand side to lefthand side. `target = "Sepal.Length = 10"`

**Comment by strengejacke** [comment]
I see, you want to arrive at [this clever API design](https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html). 😄

**Comment by DominiqueMakowski** [comment]
I MUST ADMIT that I'm quite happy about how easy it was to add that, how easy the code is and how sleek and intuitive the API is ☺️ 😁 

``` r
library(estimate)

visualisation_matrix(iris, target = c("Sepal.Length = 3", "Species"))
#>   Sepal.Length    Species Sepal.Width Petal.Length Petal.Width
#> 1            3     setosa    3.057333        3.758    1.199333
#> 2            3 versicolor    3.057333        3.758    1.199333
#> 3            3  virginica    3.057333        3.758    1.199333
visualisation_matrix(iris, target = c("Sepal.Length = c(3, 1)", "Species = 'setosa'"))
#>   Sepal.Length Species Sepal.Width Petal.Length Petal.Width
#> 1            3  setosa    3.057333        3.758    1.199333
#> 2            1  setosa    3.057333        3.758    1.199333
```

<sup>Created on 2019-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
